---
title: "The Economic Effects Of Trade Policy Uncertainty"

status: "Published"
year: 2020
order: 1

summary: >
  This paper uses a novel measure of trade policy uncertainty (TPU) to study the effects of unexpected changes in policy on the U.S. economy. The paper finds that increases in TPU reduce business investment and economic activity.

pdf: "https://www.sciencedirect.com/science/article/abs/pii/S0304393219302004?via%3Dihub"

appendix-cite-as: false

citation:
  type: article-journal
  title: "The Economic Effects Of Trade Policy Uncertainty"

  author:
    - family: Caldara
      given: Dario
    - family: Iacoviello
      given: Matteo
    - family: Molligo
      given: Patrick
    - family: Prestipino
      given: Andrea
    - family: Raffo
      given: Andrea

  container-title: "Journal of Monetary Economics"
  volume: 109
  page: "38--59"
  issued:
    year: 2020
  DOI: "10.1016/j.jmoneco.2019.11.002"
  URL: "https://doi.org/10.1016/j.jmoneco.2019.11.002"

---

::: {.paper-page-links}

[Download PDF](../../files/papers/TPU_PAPER.pdf){.btn .btn-primary}

:::

## Abstract

This paper studies the effects of unexpected changes in trade policy uncertainty (TPU) on the U.S. economy. Three measures of TPU are constructed using newspaper coverage, firms’ earnings calls, and tariff rates. Firm-level and aggregate macroeconomic data reveal that increases in TPU reduce business investment. The empirical results are interpreted through the lens of a two-country general equilibrium model with nominal rigidities and firms’ export participation decisions. News and increased uncertainty about higher future tariffs reduce investment and activity.

## Code and Data

The code and data used in this paper are available at [https://www.matteoiacoviello.com/tpu.htm](https://www.matteoiacoviello.com/tpu.htm)

## Citation

Caldara, D., Iacoviello, M., Molligo, P., Prestipino, A., & Raffo, A. (2020). "The Economic Effects of Trade Policy Uncertainty." Journal of Monetary Economics, 109, 38-59.

```bibtex
@article{caldara2020economic,
  title={The economic effects of trade policy uncertainty},
  author={Caldara, Dario and Iacoviello, Matteo and Molligo, Patrick and Prestipino, Andrea and Raffo, Andrea},
  journal={Journal of Monetary Economics},
  volume={109},
  pages={38--59},
  year={2020},
  publisher={Elsevier}
}
```